version: "3.3"

services:
  map:
    build:
      context: ./map
      dockerfile: Dockerfile
    image: velo-map
    container_name: container-velo-map
    ports:
      - "5000:5000"
  profile:
    build:
      context: ./profile
      dockerfile: Dockerfile
    image: velo-profile
    container_name: container-velo-profile
    ports:
      - "5001:5001"
# todo add network