version: "3.3"

services:
  map:
    build:
      context: ./map
      dockerfile: Dockerfile
    image: velo-map
    container_name: container-velo-map
    ports:
      - "5000:5000"
# todo add network
