version: "3.3"

services:
  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    image: velo-api
    container_name: container-velo-api
    ports:
      - "5003:5003"
    env_file:
     - ./api/.env
    networks:
      - velo-network
  map:
    build:
      context: ./map
      dockerfile: Dockerfile
    image: velo-map
    container_name: container-velo-map
    ports:
      - "5000:5000"
    networks:
      - velo-network

networks:
  velo-network:
    driver: bridge

